// Mocks generated by Mockito 5.0.7 from annotations
// in password_keeper/test/business/account_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:password_keeper/business/external_interfaces/storage_interfaces.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [PasswordsStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasswordsStorage extends _i1.Mock implements _i2.PasswordsStorage {
  MockPasswordsStorage() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [AccountPublicDataStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountPublicDataStorage extends _i1.Mock
    implements _i2.AccountPublicDataStorage {
  MockAccountPublicDataStorage() {
    _i1.throwOnMissingStub(this);
  }
}
